# ==============================
# gChat Configuration
# ==============================

enabled: true
language: ru
default-chat-mode: local
log-to-console: true

# ==============================
# Локальный чат
# ==============================
local-chat:
  enabled: true
  format: "&8[Локально]"
  radius: 50
  show-silent-message: true # Добавляет сообщение (В радиусе никого нет... Тишина.

# ==============================
# Глобальный чат
# ==============================
global-chat:
  enabled: true
  format: "&8[Глобально]"

# ==============================
# Форматы групп
# ==============================
group-formats:
  owner: "%gchat_format%&c[Owner] %player_name% &7» %message%" #Верхняя группа для OP прав
  admin: "%gchat_format%&4[Admin] %player_name% &7» %message%"
  moderator: "%gchat_format%&2[Mod] %player_name% &7» %message%"
  vip: "%gchat_format%&6[VIP] %player_name% &7» %message%"
  premium: "%gchat_format%&b[Premium] %player_name% &7» %message%"
  donator: "%gchat_format%&d[Donator] %player_name% &7» %message%"
  builder: "%gchat_format%&3[Builder] %player_name% &7» %message%"

# Формат по умолчанию (если игрок не в группе)
default-format: "%gchat_format%&f%player_name% &7» %message%"

# ==============================
# Ограничения
# ==============================

# Ограничение длины сообщения
max-message-length: 256

# Кулдаун на сообщения
message-cooldown:
  enabled: true
  seconds: 3

# Кулдаун на /gchat reload
reload-cooldown: 5

allow-colors: true
allow-gradients: true
# ==============================
# Фильтр мата
# ==============================
filter:
  enabled: true
  block-message: false # true = блокировать, false = заменять на ***
  words:
    - дурак
    - идиот
    - плохое_слово

# ==============================
# Фильтр команд
# ==============================
blocked-commands:
  - "/op"
  - "/gamemode"
  - "/ban"
  - "/kick"

# ==============================
# Сообщения входа/выхода
# ==============================
join-message: "&8[&a+&8] &f%player_name%"
quit-message: "&8[&c-&8] &f%player_name%"

# ==============================
# Помощь (/gchat help)
# ==============================
help:
  - "&6§l=== gChat Help ==="
  - "&e/gchat reload §7- Перезагрузить конфигурацию"
  - "&e/gchat help §7- Показать эту помощь"
  - "&e/gchat debug §7- Debug информация"
  - "&e/g §7- Переключиться на глобальный чат"
  - "&e/g <сообщение> §7- Отправить глобальное сообщение"
  - "&e/l §7- Переключиться на локальный чат"
  - "&e/l <сообщение> §7- Отправить локальное сообщение"
  - "&e!<сообщение> §7- Разовое глобальное сообщение"
  - "&6Градиенты: §7{#RRGGBB>}Text{#RRGGBB<}"
