# ==============================
# gChat Configuration
# ==============================

enabled: true
language: ru # ru en
default-chat-mode: local
log-to-console: true

# ==============================
# Локальный чат
# ==============================
local-chat:
  enabled: true
  format: "&8[Локально]" # %gchat_format%
  radius: 50
  show-silent-message: true # Добавляет сообщение (В радиусе никого нет... Тишина.

# ==============================
# Глобальный чат
# ==============================
global-chat:
  enabled: true
  format: "&8[Глобально]" # %gchat_format%

# ==============================
# Форматы групп
# ==============================
group-formats:
  legend: "%gchat_format%{#ff69b4>}%player_name%{#8a2be2<} &7» %message%"
  emerald: "%gchat_format%{#50C878>}%player_name%{#00FF00<} &7» %message%"
  diamond: "%gchat_format%{#00BFFF>}%player_name%{#1E90FF<} &7» %message%"

# Формат по умолчанию (если игрок не в группе)
default-format: "%gchat_format%%luckperms_suffix%%player_name%&7 » %message%"

# ==============================
# Ограничения
# ==============================
max-message-length: 256

# Кулдаун на сообщения
message-cooldown:
  enabled: true
  seconds: 3

# Кулдаун на /gchat reload
reload-cooldown: 5

allow-colors: true
allow-gradients: true
# ==============================
# Фильтр мата
# ==============================
filter:
  enabled: true
  block-message: false # true = блокировать, false = заменять на ***
  words:
    - дурак
    - идиот
    - плохое_слово

# ==============================
# Фильтр команд
# ==============================
block-commands-enabled: true
blocked-commands:
  - "me"
  - "tell"
  - "msg"
  - "whisper"
  - "w"
  - "say"
  - "pl"
  - "plugins"
  - "help"
  - "?"
# ==============================
# Сообщения входа/выхода
# ==============================
join-quit-messages:
  enabled: true
  join-message: "&a+ &7%player_name% &aприсоединился к серверу"
  quit-message: "&c- &7%player_name% &cпокинул сервер"
