# ==============================
# gChat Configuration
# ==============================

enabled: true
language: ru
default-chat-mode: local
log-to-console: true 

# ==============================
# Локальный чат
# ==============================
local-chat:
  enabled: true
  format: "&8[Локально]"
  radius: 50
  show-silent-message: true # Добавляет сообщение (В радиусе никого нет... Тишина.

# ==============================
# Глобальный чат
# ==============================
global-chat:
  enabled: true
  format: "&8[Глобально]"

# ==============================
# Форматы групп
# ==============================
group-formats:
  legend: "{#ff69b4>}%player_name%{#8a2be2<} &7» %message%"
  emerald: "{#50C878>}%player_name%{#00FF00<} &7» %message%"
  diamond: "{#00BFFF>}%player_name%{#1E90FF<} &7» %message%"

# Формат по умолчанию (если игрок не в группе)
default-format: "%luckperms_suffix%%player_name%&7 » %message%"

# ==============================
# Ограничения
# ==============================

# Ограничение длины сообщения
max-message-length: 256

# Кулдаун на сообщения
message-cooldown:
  enabled: true
  seconds: 3

# Кулдаун на /gchat reload
reload-cooldown: 5

allow-colors: true
allow-gradients: true
# ==============================
# Фильтр мата
# ==============================
filter:
  enabled: true
  block-message: false # true = блокировать, false = заменять на ***
  words:
    - дурак
    - идиот
    - плохое_слово

# ==============================
# Фильтр команд
# ==============================
blocked-commands:
  - "/op"
  - "/gamemode"
  - "/ban"
  - "/kick"

# ==============================
# Сообщения входа/выхода
# ==============================
join-message: "&8[&a+&8] &f%player_name%"
quit-message: "&8[&c-&8] &f%player_name%"