name: gChat
version: 1.3.0
main: com.Gomania.gChat.GChat
api-version: 1.21
softdepend:
  - PlaceholderAPI
  - LuckPerms
commands:
  gchat:
    description: Основная команда gChat
    usage: /<command> help
    aliases: [gchat]
    permission: gchat.use

  g:
    description: Переключение или отправка глобального сообщения
    usage: /<command> [сообщение]
    permission: gchat.global

  l:
    description: Переключение или отправка локального сообщения
    usage: /<command> [сообщение]
    permission: gchat.local

  broadcast:
    description: Broadcast messages
    usage: /broadcast <номер|next|reload>
    permission: gchat.broadcast

permissions:
  gchat.*:
    description: Доступ ко всем функциям gChat
    default: op
    children:
      gchat.use: true
      gchat.reload: true
      gchat.debug: true
      gchat.global: true
      gchat.local: true
      gchat.bypass.filter: true
      gchat.bypass.cooldown: true

  gchat.use:
    description: Базовое использование gChat
    default: true

  gchat.reload:
    description: Перезагрузка конфигурации
    default: op

  gchat.debug:
    description: Получение debug информации
    default: op

  gchat.global:
    description: Использование глобального чата
    default: true

  gchat.local:
    description: Использование локального чата
    default: true

  gchat.bypass.filter:
    description: Обход фильтра мата
    default: op

  gchat.bypass.cooldown:
    description: Обход кулдауна сообщений
    default: op
